// A HEADER FILE IS WHERE WE WERE GOING TO BE PUTTING ALL
// OUU CLASSES FUNCTIONS PPROTOTYPES AND VARIABLES DECLARATIONS

#ifndef SEPARATECLASS_H
#define SEPARATECLASS_H

class separateClass {
public:
	separateClass();
};

#endif